#!/bin/bash
# Zohal Uploader - Deployment Checklist

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🪐  Zohal Uploader - Deployment Guide"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Colors
GREEN='\033[32m'
BLUE='\033[34m'
YELLOW='\033[33m'
NC='\033[0m'

echo -e "${BLUE}▸ Files Updated${NC}"
echo "  ✓ bot/handlers.py      - Modernized commands & handlers"
echo "  ✓ bot/keyboards.py     - New command list, cleaner buttons"
echo "  ✓ bot/bot.py           - Added setup_commands() call"
echo "  ✓ cli.py               - Complete rewrite (modern UI, update checks)"
echo ""

echo -e "${BLUE}▸ What to Do Next${NC}"
echo ""
echo "  1. Backup current installation:"
echo "     $ cp -r /root/zohal-uploader /root/zohal-uploader.backup"
echo ""
echo "  2. Copy updated files to production:"
echo "     $ cp bot/handlers.py /root/zohal-uploader/bot/"
echo "     $ cp bot/keyboards.py /root/zohal-uploader/bot/"
echo "     $ cp bot/bot.py /root/zohal-uploader/bot/"
echo "     $ cp cli.py /root/zohal-uploader/"
echo ""
echo "  3. Make CLI executable:"
echo "     $ chmod +x /root/zohal-uploader/cli.py"
echo ""
echo "  4. Test the CLI:"
echo "     $ /root/zohal-uploader/cli.py"
echo ""
echo "  5. If setup is already done, restart the bot:"
echo "     $ systemctl restart zohal"
echo ""
echo "  6. Check bot commands in Telegram:"
echo "     • Type / in DM to see command menu"
echo "     • Should show: /start, /help, /upload, /s3, /settings, /stats"
echo ""

echo -e "${BLUE}▸ Key Improvements${NC}"
echo ""
echo "  Telegram Bot:"
echo "    • Slash commands (/start, /help, etc.)"
echo "    • Command menu in Telegram client"
echo "    • Cleaner button labels"
echo "    • Better handler organization"
echo ""
echo "  CLI Experience:"
echo "    • Modern colored interface"
echo "    • Auto-update checks (every run)"
echo "    • Telegram notifications on updates"
echo "    • Interactive setup wizard"
echo "    • Live status dashboard"
echo "    • User management UI"
echo "    • One-click update"
echo "    • Service control buttons"
echo ""

echo -e "${BLUE}▸ Testing Checklist${NC}"
echo ""
echo "  Before Production:"
echo "    [ ] Run ./cli.py and verify menu loads"
echo "    [ ] Check 'View Status' shows resources"
echo "    [ ] Verify 'Manage Users' works"
echo "    [ ] Test 'Bot Control' restart"
echo "    [ ] Check 'Update' (should say up-to-date if you're on latest)"
echo ""
echo "  In Telegram:"
echo "    [ ] Type / and see command menu"
echo "    [ ] Send /start to see welcome"
echo "    [ ] Send /help to see features"
echo "    [ ] Verify admin buttons appear (👥 Users, 📊 Stats)"
echo ""

echo -e "${BLUE}▸ Troubleshooting${NC}"
echo ""
echo "  CLI won't start?"
echo "    • Check Python 3.10+: python3 --version"
echo "    • Verify modules: pip install httpx psutil"
echo ""
echo "  Bot commands not showing?"
echo "    • Restart bot: systemctl restart zohal"
echo "    • Wait 10 seconds for Telegram to refresh"
echo ""
echo "  Update check failing?"
echo "    • Check internet: curl -I https://api.github.com"
echo "    • Bot token must be valid for Telegram notifications"
echo ""

echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  Ready to deploy! Follow the steps above.${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
